site_name: RadarBot Documentation
site_url: https://docs.radarbot.xyz
repo_url: https://github.com/radarbot-team/radarbot-docs
repo_name: radarbot-docs
copyright: Powered by <a href="https://vercel.com/?utm_source=radarbot-team&utm_campaign=oss" target="_blank">
  <img src="/assets/images/vercel-light-logo.svg" alt="Vercel Logo"></a>


theme:
  name: material
  custom_dir: overrides
  font:
    text: Inter
  logo: assets/images/RadarBotLogo.png

  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # Temporarily deactivated to provide support for Discord browser + anchor links
    # - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
  favicon: assets/images/RadarBotLogo.png

extra_css:
  - stylesheets/extra.css
  - stylesheets/navigation.css

plugins:
  - search:
      lang: en
  - awesome-pages
  - git-revision-date-localized:
      type: date
  - redirects:
      redirect_maps:
        'start/guides.md': 'radarbot-en/guides/index.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html